### ISSUE TITLE
Linker doesn't resolve relocations when relocatable flag is used

### ISSUE THREAD

**Issue by calebh** [purseclab/Patcherex2#30]
I've been working on aarch64 support for the copy and micropatch fork and I've come across an issue with the use of the `-relocatable` flag during the linking process. This flag is used in `compiler.py` and `llvm_recomp.py`.

It seems that relative relocations are not resolved when the `-relocatable` flag is used. See this Stackoverflow post for more details: https://stackoverflow.com/questions/35324636/resolve-relative-relocations-in-partial-link

Merely removing the `-relocatable` flag causes a bunch of other errors. When the `base=0`, we get an error trace like this:
```
ERROR    | 2024-05-02 11:25:19,643 | patcherex2.components.compilers.compiler | ld.lld-15: error: /tmp/tmp_uu_rkga/linker.ld:1: unable to move location counter backward for: .patcherex2
ld.lld-15: error: /tmp/tmp_uu_rkga/linker.ld:1: unable to move location counter backward for: .patcherex2
ld.lld-15: error: section .patcherex2 at 0x34 of size 0xFFFFFFFFFFFFFFF0 exceeds available address space
ld.lld-15: error: section .eh_frame file range overlaps with .comment
>>> .eh_frame range is [0x10000, 0x10033]
>>> .comment range is [0x10024, 0x1005A]

ld.lld-15: error: section .comment file range overlaps with .patcherex2
>>> .comment range is [0x10024, 0x1005A]
>>> .patcherex2 range is [0x10034, 0x10023]

Traceback (most recent call last):
  File "/home/caleb/Documents/vibesproject/Patcherex2/tests/test_binaries/aarch64/iip_c.py", line 26, in <module>
    p.apply_patches()
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patcherex.py", line 100, in apply_patches
    patch.apply(self)
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patches/instruction_patches.py", line 224, in apply
    self._apply_c(p)
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patches/instruction_patches.py", line 340, in _apply_c
    p.utils.insert_trampoline_code(
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/components/utils/utils.py", line 70, in insert_trampoline_code
    self.p.compiler.compile(
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/components/compilers/compiler.py", line 96, in compile
    raise e
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/components/compilers/compiler.py", line 93, in compile
    print(subprocess.run(args, check=True, capture_output=True))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ld.lld-15', '/tmp/tmp_uu_rkga/obj.o', '-T', '/tmp/tmp_uu_rkga/linker.ld', '-o', '/tmp/tmp_uu_rkga/obj_linked.o']' returned non-zero exit status 1.
```

For the nonzero `base`, the linking process completes successfully but results in a different error:
```
Traceback (most recent call last):
  File "/home/caleb/Documents/vibesproject/Patcherex2/tests/test_binaries/aarch64/iip_c.py", line 26, in <module>
    p.apply_patches()
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patcherex.py", line 100, in apply_patches
    patch.apply(self)
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patches/instruction_patches.py", line 224, in apply
    self._apply_c(p)
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/patches/instruction_patches.py", line 340, in _apply_c
    p.utils.insert_trampoline_code(
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/components/utils/utils.py", line 124, in insert_trampoline_code
    compiled_code = self.p.compiler.compile(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/caleb/Documents/vibesproject/Patcherex2/src/patcherex2/components/compilers/compiler.py", line 108, in compile
    compiled = ld.memory.load(
               ^^^^^^^^^^^^^^^
  File "/home/caleb/Documents/vibesproject/Patcherex2/venv/lib/python3.11/site-packages/cle/memory.py", line 391, in load
    raise KeyError(addr)
KeyError: 203024
```

This issue crops up when we attempt to compile a copy-and-micropatch C file which has an `extern _CALLBACK` function. The `_CALLBACK` symbol ends up being a 1 instruction relative jump. On `aarch64` this will cause the program to jump to the jump instruction, which causes an infinite loop. I have an example to reproduce this issue, however it uses the Draper branch. It is based off of the `iip_c` test case found in the `tests/test_binaries/aarch64` folder. I have attached the relevant compiled `iip_c` test case and the InsertInstructionPatch C script: [iip_c.zip](https://github.com/purseclab/Patcherex2/files/15190794/iip_c.zip)

If you look in iip_c.patched you will see the infinite loop (highlighted in green) in Ghidra:
![image](https://github.com/purseclab/Patcherex2/assets/53128179/2ce3386f-241a-440f-a886-e536b087e392)

The correct assembly code should be `01 00 00 14`. If you don't use the `-relocatable` flag with nonzero base and look at `obj_linked.o` as created in the `/tmp` directory, you will see that the linker does correctly resolve this branch instruction. Even though the linking succeeds, the program then fails with the `KeyError` that I posted previously.

Some other possibly helpful links:
- https://stackoverflow.com/questions/29391965/what-is-partial-linking-in-gnu-linker
- https://eli.thegreenplace.net/2011/08/25/load-time-relocation-of-shared-libraries/

**Comment by DennyDai** [comment]
According to the log
```bash
WARNING  | 2024-05-08 01:13:31,803 | cle.backends.elf.relocation | Unknown reloc 282 on AARCH64
WARNING  | 2024-05-08 01:13:31,804 | cle.backends.elf.relocation | Unknown reloc 261 on AARCH64
```

The issue appears to be that [cle](https://github.com/angr/cle) hasn't implemented relocation types 282 and 261 (`R_AARCH64_JUMP26` and `R_AARCH64_PREL32`). 

I've implemented them and made a PR, before it gets merged, you can use [my fork](https://github.com/DennyDai/cle) for testing.

**Comment by calebh** [comment]
Got it, this change seemed to fix the problem. So based on your change, it looks like the information about the location for `_CALLBACK` was indeed included in the linked ELF, and it is the job of the runtime loader to patch in the symbol. The issue really was that cle didn't support that particular relocation. Is this correct?

**Comment by DennyDai** [comment]
@calebh Yes, that's correct.

**Comment by calebh** [comment]
I have another ARM64 relocation error from one of our test cases:

```
WARNING  | 2024-05-08 13:58:10,162 | cle.backends.elf.relocation | Unknown reloc 299 on AARCH64
```

**Comment by DennyDai** [comment]
@calebh I've fixed them and waiting for PR to be merged. You can use my fork for testing for now.
